### ISSUE TITLE
not saving password for one of my accounts

### ISSUE THREAD

**Issue by sentix001** [lemasato/Steam-Account-Switcher#6] opened 2020-01-24 05:17 UTC
not saving password for one of my accounts

**Comment by lemasato** [comment] 2020-01-24 14:48
Saved passwords are managed by Steam, not this tool.
Make sure to have "Remember my password" ticked when logging on Steam. Then, when you need to switch accounts, use Steam Account Switcher and never use the "log out" option from Steam.

**Comment by sentix001** [comment] 2020-01-24 14:50
Hi i am doing all you said at first it was ok but now it wont hold tried 10
times, deleted the user and reput it no luck

**Comment by darklordabc** [comment] 2020-06-23 03:02
Yeah this shit is broken, maybe steam changed how it sores passwords, but this tool no longer remebers passwords (It does sometimes, but it will soon forget the password), this tool is now useless.

**Comment by lemasato** [comment] 2020-06-23 20:39
Still work fine for me like it always has
The cookies stored by Steam will eventually expire after a few weeks of not logging on the account, but that only makes sense

If it suddenly stops working then I'm afraid there really isn't much I can do to help as the issue is system/steam related and not related to this app :/

The only thing I can recommend would be to try a "clean install" of Steam, but I can't guarantee that it'll fix anything. This can be done by deleting everything in the Steam folder except `Steam.exe, SteamApps, UserData` and then starting Steam.exe as admin

**Comment by lemasato** [comment] 2020-08-18 19:14
Managed to log into an account that I hadn't logged in for weeks without any issue.
Obviously at some point the cookie has to expire. It could happen with time, hardware change, or windows update.

Closing this as it's not an issue related to SAS itself.

**Closed by lemasato** 2020-08-18 19:14 UTC
